---
- hosts: all
  become: True
  gather_facts: yes

  tasks: 
    - name: Create a file
      file:
        path: /home/ec2-user/testing_playbookfile
        mode: '0400'
        state: touch
    
    - name: Create a file
      file:
        path: /home/ec2-user/testing_playbookfile
        mode: '0400'
        state: absent